asdf:
  src: "{{ dotfiles.home }}/.asdf/asdf.sh"
  bin: "{{ dotfiles.home }}/.asdf/bin/asdf"
erlang:
  versions:
    - 24.2
  dependencies:
    - build-essential
    - autoconf
    - m4
    - libncurses5-dev
    - libwxgtk3.0-gtk3-dev
    - libgl1-mesa-dev
    - libglu1-mesa-dev
    - libpng-dev
    - libssh-dev
    - unixodbc-dev
    - xsltproc
    - fop
elixir:
  versions:
    - 1.13.1
ruby:
  versions:
    - 2.6.3
  dependencies:
    - autoconf
    - bison
    - build-essential
    - libssl-dev
    - libyaml-dev
    - libreadline6-dev
    - zlib1g-dev
    - libncurses5-dev
    - libffi-dev
    - libgdbm6
    - libgdbm-dev
    - libdb-dev
nodejs:
  versions:
    - 17.3.0
  dependencies:
    - dirmngr
    - gpg
