- name: Set up local workstation
  hosts: local
  vars_files:
    - ./vars/custom.yml
  roles:
    - role: base
      tags:
        - base
    - role: git
      tags:
        - git
    - role: zsh
      tags:
        - zsh
    - role: tmux
      tags:
        - tmux
    - role: fzf
      tags:
        - fzf
    - role: docker
      tags:
        - docker
    - role: asdf
      tags:
        - asdf
    - role: erlang
      tags:
        - erlang
    - role: elixir
      tags:
        - elixir
    - role: nodejs
      tags:
        - nodejs
    - role: haskell
      tags:
        - haskell
    - role: neovim
      tags:
        - neovim
