- name: Engage!
  hosts: local
  vars_files:
    - ./vars/secrets.yml
  roles:
    - role: base
      tags:
        - base
    - role: tmux
      tags:
        - tmux
    - role: crew
      tags:
        - crew
    - role: vim
      tags:
        - vim
    - role: extras
      tags:
        - extras
