docker_dependencies:
  - apt-transport-https
  - ca-certificates
  - gnupg2
  - software-properties-common

docker_repository: "deb [arch=amd64] https://download.docker.com/linux/debian buster stable"

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io

docker_compose_version: 1.25.4
