visual_code_link: "https://go.microsoft.com/fwlink/?LinkID=760868"

visual_code_extensions:
  - "ms-azuretools.vscode-docker"
  - "ms-vscode-remote.remote-containers"
  - "dart-code.dart-code"
  - "dart-code.flutter"
  - "saratravi.elixir-formatter"
  - "jakebecker.elixir-ls"
  - "mjmcloug.vscode-elixir"
  - "bradlc.vscode-tailwindcss"
