---
###############################################################################
# Vim installation

- name: Neovim | Installs Neovim | apt
  become: yes
  become_user: root
  apt:
    name: neovim
    state: present

- name: Neovim | Installs Powerline | apt
  become: yes
  become_user: root
  apt:
    name: powerline
    state: present

- name: Neovim | Creates {{ neovim_home }} | file
  file:
    path: "{{ neovim_home }}"
    state: directory
    mode: '0755'

- name: Neovim | Links init.vim file | file
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/init.vim.link"
    dest: "{{ neovim_home }}/init.vim"
    state: link
    force: yes

- name: Neovim | Links tabs.vim file | file
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/tabs.vim.link"
    dest: "{{ neovim_home }}/tabs.vim"
    state: link
    force: yes

- name: Neovim | Links mkdir.vim file | file
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/mkdir.vim.link"
    dest: "{{ neovim_home }}/mkdir.vim"
    state: link
    force: yes

- name: Neovim | Links fastlane.vim file | file
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/fastlane.vim.link"
    dest: "{{ neovim_home }}/fastlane.vim"
    state: link
    force: yes

- name: Neovim | Links erlang.vim file | file
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/erlang.vim.link"
    dest: "{{ neovim_home }}/erlang.vim"
    state: link
    force: yes

- name: Neovim | Links elixir-ls.vim file | file
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/elixir-ls.vim.link"
    dest: "{{ neovim_home }}/elixir-ls.vim"
    state: link
    force: yes

- name: Neovim | Links coc.vim file | file
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/coc.vim.link"
    dest: "{{ neovim_home }}/coc.vim"
    state: link
    force: yes

- name: Neovim | Links coc-settings.json file | file
  file:
    src: "{{ dotfiles_home }}/roles/neovim/files/coc-settings.json.link"
    dest: "{{ neovim_home }}/coc-settings.json"
    state: link
    force: yes

- name: Neovim | Clones vim-plug | git
  git:
    repo: "https://github.com/junegunn/vim-plug.git"
    dest: "{{ neovim_home }}/bootstrap/vim-plug"
    clone: yes
    update: yes
    force: yes

- name: Neovim | Create autoload folder | file
  file:
    dest: "{{ dotfiles_user_home }}/.local/share/nvim/site/autoload"
    state: directory
    mode: '0755'

- name: Neovim | Links plug.vim to autoload | file
  file:
    src: "{{ neovim_home }}/bootstrap/vim-plug/plug.vim"
    dest: "{{ dotfiles_user_home }}/.local/share/nvim/site/autoload/plug.vim"
    state: link
    force: yes

- name: Neovim | Installs plugins | command
  command: vim +PlugInstall +qall
